// <auto-generated />
using BackendPortafolio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendPortafolio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220193339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendPortafolio.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlDemo")
                        .HasColumnType("text")
                        .HasColumnName("url_demo");

                    b.Property<string>("UrlRepositorio")
                        .HasColumnType("text")
                        .HasColumnName("url_repositorio");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("proyectos");
                });

            modelBuilder.Entity("BackendPortafolio.Models.ProyectoTecnologia", b =>
                {
                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<int>("TecnologiaId")
                        .HasColumnType("integer")
                        .HasColumnName("tecnologia_id");

                    b.HasKey("ProyectoId", "TecnologiaId");

                    b.HasIndex("TecnologiaId");

                    b.ToTable("proyecto_tecnologias");
                });

            modelBuilder.Entity("BackendPortafolio.Models.Tecnologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tecnologias");
                });

            modelBuilder.Entity("BackendPortafolio.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("BackendPortafolio.Models.Proyecto", b =>
                {
                    b.HasOne("BackendPortafolio.Models.Usuario", "Usuario")
                        .WithMany("Proyectos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendPortafolio.Models.ProyectoTecnologia", b =>
                {
                    b.HasOne("BackendPortafolio.Models.Proyecto", "Proyecto")
                        .WithMany("ProyectoTecnologias")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendPortafolio.Models.Tecnologia", "Tecnologia")
                        .WithMany("ProyectoTecnologias")
                        .HasForeignKey("TecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Tecnologia");
                });

            modelBuilder.Entity("BackendPortafolio.Models.Proyecto", b =>
                {
                    b.Navigation("ProyectoTecnologias");
                });

            modelBuilder.Entity("BackendPortafolio.Models.Tecnologia", b =>
                {
                    b.Navigation("ProyectoTecnologias");
                });

            modelBuilder.Entity("BackendPortafolio.Models.Usuario", b =>
                {
                    b.Navigation("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
